### ISSUE TITLE
实例代码有错

### ISSUE THREAD

**Issue by 157299182** [TshineZheng/DragonbonesCocos2dx#2]
HelloDragonBonesScene.lua
22行,self._factory = db.CCFactory:new()并不能运行通过
改为self._factory = db.CCFactory:getInstance()则没问题了，是我配置错了，还是的确有此问题

**Comment by 157299182** [comment]
环境为xcode,mac

**Comment by TshineZheng** [comment]
@157299182 确实是实例代码错误，漏提交了，感谢回馈
